apiVersion: apps/v1
kind: Deployment
metadata:
  name: euroautoparts-googlesheets-api
  namespace: prod
  labels:
    app: euroautoparts-googlesheets-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: euroautoparts-googlesheets-api
  template:
    metadata:
      labels:
        app: euroautoparts-googlesheets-api
    spec:
      containers:
        - name: euroautoparts-googlesheets-api
          image: ghcr.io/win-ts/euroautoparts-googlesheets-api:x86
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          envFrom:
            - secretRef:
                name: landing-page-secret
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/gcp-credentials/gcp-credentials.json"
          volumeMounts:
            - name: gcp-credentials
              mountPath: "/etc/gcp-credentials"
              readOnly: true
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
      imagePullSecrets:
        - name: ghcr-secret
